services:
  postgres:
    image: postgres:17-alpine
    container_name: library_db
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: librarypassword
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: library_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@library.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
